## Selección de datos

In [1]:
import pandas as pd
sales = pd.read_csv("data\\sales.csv")

sales.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [2]:
# Seleccionando columnas específicas
sales1 = sales[["store", "type", "department", "date", "weekly_sales"]]
sales1.head()

   store type  department        date  weekly_sales
0      1    A           1  2010-02-05      24924.50
1      1    A           1  2010-03-05      21827.90
2      1    A           1  2010-04-02      57258.43
3      1    A           1  2010-05-07      17413.94
4      1    A           1  2010-06-04      17558.09

In [3]:
# Seleccioando todas las columnas a excepción de 2
columnas_excluidas = ["fuel_price_usd_per_l", "unemployment"]
sales2 = sales.drop(columns=columnas_excluidas)
sales2.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c
0,0,1,A,1,2010-02-05,24924.50,False,5.727778
1,1,1,A,1,2010-03-05,21827.90,False,8.055556
2,2,1,A,1,2010-04-02,57258.43,False,16.816667
3,3,1,A,1,2010-05-07,17413.94,False,22.527778
4,4,1,A,1,2010-06-04,17558.09,False,27.050000

## Eliminando datos duplicados

In [4]:
# Eliminar duplicados de la combinación store y type
stores_types = sales.drop_duplicates(subset=["store", "type"])
stores_types.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
901,901,2,A,1,2010-02-05,35034.06,False,4.550000,0.679451,8.324
1798,1798,4,A,1,2010-02-05,38724.42,False,6.533333,0.686319,8.623
2699,2699,6,A,1,2010-02-05,25619.00,False,4.683333,0.679451,7.259
3593,3593,10,B,1,2010-02-05,40212.84,False,12.411111,0.782478,9.765

In [5]:
# Eliminar duplicados de la combinación store y department
stores_depts = sales.drop_duplicates(subset=["store", "department"])
stores_depts.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
12,12,1,A,2,2010-02-05,50605.27,False,5.727778,0.679451,8.106
24,24,1,A,3,2010-02-05,13740.12,False,5.727778,0.679451,8.106
36,36,1,A,4,2010-02-05,39954.04,False,5.727778,0.679451,8.106
48,48,1,A,5,2010-02-05,32229.38,False,5.727778,0.679451,8.106

In [6]:
# Eliminar duplicados por fecha de las ventas en feriado
holiday_dates = sales[sales["is_holiday"]==True].drop_duplicates(subset="date")
holiday_dates.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
498,498,1,A,45,2010-09-10,11.47,True,25.938889,0.677602,7.787
691,691,1,A,77,2011-11-25,1431.00,True,15.633333,0.854861,7.866
2315,2315,4,A,47,2010-02-12,498.00,True,-1.755556,0.679715,8.623
6735,6735,19,A,39,2012-09-07,13.41,True,22.333333,1.076766,8.193
6810,6810,19,A,47,2010-12-31,-449.00,True,-1.861111,0.881278,8.067

## Conteo de datos

In [10]:
# Conteo de tiendas por tipo
store_count = stores_types["type"].value_counts()
print(store_count)

type
A    11
B     1
Name: count, dtype: int64

In [8]:
# Conteo de tiendas por tipo (representado en porcentaje)
store_prop = stores_types["type"].value_counts(normalize=True)
print(store_prop)

type
A    0.916667
B    0.083333
Name: proportion, dtype: float64

In [9]:
# Counteo de tiendas por departamento ordenado de forma descendente
dept_counts = stores_depts["department"].value_counts(sort=True, ascending=False)
print(dept_counts)

department
1     12
2     12
3     12
4     12
5     12
      ..
37    10
48     8
50     6
39     4
43     2
Name: count, Length: 80, dtype: int64

## Agrupamiento de datos con groupby

In [11]:
# Agrupando por typo de tienda
sales_type = sales.groupby("type")
sales_type["weekly_sales"].sum()

type
A    2.337163e+08
B    2.317840e+07
Name: weekly_sales, dtype: float64

In [14]:
# Calculando la venta total por el campo weekly_sales
sales_all = sales["weekly_sales"].sum()
print(sales_all)

256894718.89999998

In [15]:
# Calculando la venta total de las tiendas de tipo A
sales_A = sales[sales["type"]=="A"]["weekly_sales"].sum()
print(sales_A)

233716315.01

In [17]:
# Calculando la venta total de las tiendas de tipo B
sales_B = sales[sales["type"]=="B"]["weekly_sales"].sum()
print(sales_B)

23178403.89

In [18]:
# Calculando la venta total de las tiendas de tipo C
sales_C = sales[sales["type"]=="C"]["weekly_sales"].sum()
print(sales_C)

0.0

In [19]:
# Hallar la proporción de ventas semanales por tipo de tienda con respecto al total
sales_prop = [sales_A, sales_B, sales_C] / sales_all
print(sales_prop)

[0.9097747 0.0902253 0.       ]

In [20]:
# Hallando datos estadísticos con agrupación
sales_stats = sales.groupby("type")["weekly_sales"].agg(['min', 'max', 'sum', 'mean', 'median'])
print(sales_stats)

         min        max           sum          mean    median
type
A    -1098.0  293966.05  2.337163e+08  23674.667242  11943.92
B     -798.0  232558.51  2.317840e+07  25696.678370  13336.08

In [23]:
# Hallando datos estadísticos con agrupación (de varias columnas)
sales_stats_multi = sales.groupby("type")[["weekly_sales", "fuel_price_usd_per_l"]].agg(['min', 'max'])
print(sales_stats_multi)

     weekly_sales            fuel_price_usd_per_l
              min        max                  min       max
type
A         -1098.0  293966.05             0.664129  1.107410
B          -798.0  232558.51             0.760023  1.107674

In [25]:
# Agrupando dos columnas
sales_type_dept = sales.groupby(["type", "department"])["weekly_sales"].agg(['min', 'max', 'sum'])
print(sales_type_dept)

                      min        max         sum
type department
A    1            9446.29  149743.97  4086947.75
     2           42431.88   93677.66  8923220.96
     3            6150.20   69512.63  2265120.39
     4           28762.65   66912.92  5845672.68
     5           11665.55  103531.25  4596373.50
...                   ...        ...         ...
B    94            -12.60    1903.68     1937.35
     95          60655.66   94868.27   924985.23
     96           8348.61   10576.00   114342.46
     97           5064.61    6720.96    69946.48
     98             -2.25    1075.30     2609.14

[157 rows x 3 columns]

## Pivoteo de tablas

In [26]:
# Ver la data original de ventas
sales.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [27]:
# Pivoteando la tabla con el promedio de las ventas semanales por tipo
sales_by_type = sales.pivot_table(values="weekly_sales", index="type")
sales_by_type

      weekly_sales
type
A     23674.667242
B     25696.678370

In [29]:
# Pivoteando la tabla de las ventas semanales por tipo, hallando max, min, sum y prom
sales_by_type_stats = sales.pivot_table(values="weekly_sales", index="type", aggfunc=["min", "max", "sum", "mean"])
sales_by_type_stats

              min          max           sum          mean
     weekly_sales weekly_sales  weekly_sales  weekly_sales
type
A         -1098.0    293966.05  2.337163e+08  23674.667242
B          -798.0    232558.51  2.317840e+07  25696.678370

In [31]:
# Pivoteando la tabla por dos columnas (departamento y tipo) con el total y promedio de las ventas semanales
sales_dept_type = sales.pivot_table(values="weekly_sales", index="department", columns="type", aggfunc=["sum", "mean"])
sales_dept_type

                    sum                       mean
type                  A           B              A              B
department
1            4086947.75   528607.52   30961.725379   44050.626667
2            8923220.96  1355502.32   67600.158788  112958.526667
3            2265120.39   366967.86   17160.002955   30580.655000
4            5845672.68   614635.85   44285.399091   51219.654167
5            4596373.50   758842.50   34821.011364   63236.875000
...                 ...         ...            ...            ...
95          16359259.90   924985.23  123933.787121   77082.102500
96           2692247.40   114342.46   21367.042857    9528.538333
97           3758207.24    69946.48   28471.266970    5828.873333
98           1699555.86     2609.14   12875.423182     217.428333
99             46632.21         NaN     379.123659            NaN

[80 rows x 4 columns]

In [32]:
# Pivoteando la tabla por dos columnas (departamento y tipo) con el total y promedio de las ventas semanales, llenado ceros en donde no haya data
sales_dept_type_z = sales.pivot_table(values="weekly_sales", index="department", columns="type", fill_value=0)
sales_dept_type_z

type                    A              B
department
1            30961.725379   44050.626667
2            67600.158788  112958.526667
3            17160.002955   30580.655000
4            44285.399091   51219.654167
5            34821.011364   63236.875000
...                   ...            ...
95          123933.787121   77082.102500
96           21367.042857    9528.538333
97           28471.266970    5828.873333
98           12875.423182     217.428333
99             379.123659       0.000000

[80 rows x 2 columns]

In [33]:
# Pivoteando la tabla por dos columnas con el total y promedio de las ventas semanales, llenado ceros en donde no haya data y totalizada
sales_dept_type_zt = sales.pivot_table(values="weekly_sales", index="department", columns="type", fill_value=0, margins=True)
sales_dept_type_zt

type                   A              B           All
department
1           30961.725379   44050.626667  32052.467153
2           67600.158788  112958.526667  71380.022778
3           17160.002955   30580.655000  18278.390625
4           44285.399091   51219.654167  44863.253681
5           34821.011364   63236.875000  37189.000000
...                  ...            ...           ...
96          21367.042857    9528.538333  20337.607681
97          28471.266970    5828.873333  26584.400833
98          12875.423182     217.428333  11820.590278
99            379.123659       0.000000    379.123659
All         23674.667242   25696.678370  23843.950149

[81 rows x 3 columns]